local _M = {}

_M["10101"] = {
	
	["id"] = 10101,	
	["skillid"] = 101,	
	["level"] = 1,	
	["money"] = 10,	
	["hp"] = 10,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 3,	
	["morale"] = 10,	
	["cd"] = 10,
}
_M["10102"] = {
	
	["id"] = 10102,	
	["skillid"] = 101,	
	["level"] = 2,	
	["money"] = 20,	
	["hp"] = 20,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 10,	
	["cd"] = 10,
}
_M["10103"] = {
	
	["id"] = 10103,	
	["skillid"] = 101,	
	["level"] = 3,	
	["money"] = 30,	
	["hp"] = 30,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 5,	
	["morale"] = 10,	
	["cd"] = 10,
}
_M["10104"] = {
	
	["id"] = 10104,	
	["skillid"] = 101,	
	["level"] = 4,	
	["money"] = 40,	
	["hp"] = 40,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 6,	
	["morale"] = 10,	
	["cd"] = 10,
}
_M["10105"] = {
	
	["id"] = 10105,	
	["skillid"] = 101,	
	["level"] = 5,	
	["money"] = 50,	
	["hp"] = 50,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 7,	
	["morale"] = 10,	
	["cd"] = 10,
}
_M["10201"] = {
	
	["id"] = 10201,	
	["skillid"] = 102,	
	["level"] = 1,	
	["money"] = 10,	
	["hp"] = 0,	
	["attack"] = 20,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 3,	
	["morale"] = 10,	
	["cd"] = 10,
}
_M["10202"] = {
	
	["id"] = 10202,	
	["skillid"] = 102,	
	["level"] = 2,	
	["money"] = 20,	
	["hp"] = 0,	
	["attack"] = 30,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 10,	
	["cd"] = 10,
}
_M["10203"] = {
	
	["id"] = 10203,	
	["skillid"] = 102,	
	["level"] = 3,	
	["money"] = 30,	
	["hp"] = 0,	
	["attack"] = 40,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 5,	
	["morale"] = 10,	
	["cd"] = 10,
}
_M["10204"] = {
	
	["id"] = 10204,	
	["skillid"] = 102,	
	["level"] = 4,	
	["money"] = 40,	
	["hp"] = 0,	
	["attack"] = 50,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 6,	
	["morale"] = 10,	
	["cd"] = 10,
}
_M["10205"] = {
	
	["id"] = 10205,	
	["skillid"] = 102,	
	["level"] = 5,	
	["money"] = 50,	
	["hp"] = 0,	
	["attack"] = 60,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 7,	
	["morale"] = 10,	
	["cd"] = 10,
}
_M["10301"] = {
	
	["id"] = 10301,	
	["skillid"] = 103,	
	["level"] = 1,	
	["money"] = 10,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 20,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 3,	
	["morale"] = 10,	
	["cd"] = 10,
}
_M["10302"] = {
	
	["id"] = 10302,	
	["skillid"] = 103,	
	["level"] = 2,	
	["money"] = 20,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 30,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 10,	
	["cd"] = 10,
}
_M["10303"] = {
	
	["id"] = 10303,	
	["skillid"] = 103,	
	["level"] = 3,	
	["money"] = 30,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 40,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 5,	
	["morale"] = 10,	
	["cd"] = 10,
}
_M["10304"] = {
	
	["id"] = 10304,	
	["skillid"] = 103,	
	["level"] = 4,	
	["money"] = 40,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 50,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 6,	
	["morale"] = 10,	
	["cd"] = 10,
}
_M["10305"] = {
	
	["id"] = 10305,	
	["skillid"] = 103,	
	["level"] = 5,	
	["money"] = 50,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 60,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 7,	
	["morale"] = 10,	
	["cd"] = 10,
}
_M["10401"] = {
	
	["id"] = 10401,	
	["skillid"] = 104,	
	["level"] = 1,	
	["money"] = 10,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 10,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 3,	
	["morale"] = 10,	
	["cd"] = 10,
}
_M["10402"] = {
	
	["id"] = 10402,	
	["skillid"] = 104,	
	["level"] = 2,	
	["money"] = 20,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 20,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 10,	
	["cd"] = 10,
}
_M["10403"] = {
	
	["id"] = 10403,	
	["skillid"] = 104,	
	["level"] = 3,	
	["money"] = 30,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 30,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 5,	
	["morale"] = 10,	
	["cd"] = 10,
}
_M["10404"] = {
	
	["id"] = 10404,	
	["skillid"] = 104,	
	["level"] = 4,	
	["money"] = 40,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 40,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 6,	
	["morale"] = 10,	
	["cd"] = 10,
}
_M["10405"] = {
	
	["id"] = 10405,	
	["skillid"] = 104,	
	["level"] = 5,	
	["money"] = 50,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 50,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 7,	
	["morale"] = 10,	
	["cd"] = 10,
}
_M["10501"] = {
	
	["id"] = 10501,	
	["skillid"] = 105,	
	["level"] = 1,	
	["money"] = 10,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 10,	
	["attack_speed"] = 0,	
	["time_duration"] = 3,	
	["morale"] = 10,	
	["cd"] = 10,
}
_M["10502"] = {
	
	["id"] = 10502,	
	["skillid"] = 105,	
	["level"] = 2,	
	["money"] = 20,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 20,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 10,	
	["cd"] = 10,
}
_M["10503"] = {
	
	["id"] = 10503,	
	["skillid"] = 105,	
	["level"] = 3,	
	["money"] = 30,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 30,	
	["attack_speed"] = 0,	
	["time_duration"] = 5,	
	["morale"] = 10,	
	["cd"] = 10,
}
_M["10504"] = {
	
	["id"] = 10504,	
	["skillid"] = 105,	
	["level"] = 4,	
	["money"] = 40,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 40,	
	["attack_speed"] = 0,	
	["time_duration"] = 6,	
	["morale"] = 10,	
	["cd"] = 10,
}
_M["10505"] = {
	
	["id"] = 10505,	
	["skillid"] = 105,	
	["level"] = 5,	
	["money"] = 50,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 50,	
	["attack_speed"] = 0,	
	["time_duration"] = 7,	
	["morale"] = 10,	
	["cd"] = 10,
}
_M["10601"] = {
	
	["id"] = 10601,	
	["skillid"] = 106,	
	["level"] = 1,	
	["money"] = 10,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 10,	
	["time_duration"] = 3,	
	["morale"] = 10,	
	["cd"] = 10,
}
_M["10602"] = {
	
	["id"] = 10602,	
	["skillid"] = 106,	
	["level"] = 2,	
	["money"] = 20,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 20,	
	["time_duration"] = 4,	
	["morale"] = 10,	
	["cd"] = 10,
}
_M["10603"] = {
	
	["id"] = 10603,	
	["skillid"] = 106,	
	["level"] = 3,	
	["money"] = 30,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 30,	
	["time_duration"] = 5,	
	["morale"] = 10,	
	["cd"] = 10,
}
_M["10604"] = {
	
	["id"] = 10604,	
	["skillid"] = 106,	
	["level"] = 4,	
	["money"] = 40,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 40,	
	["time_duration"] = 6,	
	["morale"] = 10,	
	["cd"] = 10,
}
_M["10605"] = {
	
	["id"] = 10605,	
	["skillid"] = 106,	
	["level"] = 5,	
	["money"] = 50,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 50,	
	["time_duration"] = 7,	
	["morale"] = 10,	
	["cd"] = 10,
}
_M["10701"] = {
	
	["id"] = 10701,	
	["skillid"] = 107,	
	["level"] = 1,	
	["money"] = 10,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 20,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 3,	
	["morale"] = 10,	
	["cd"] = 10,
}
_M["10702"] = {
	
	["id"] = 10702,	
	["skillid"] = 107,	
	["level"] = 2,	
	["money"] = 20,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 30,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 10,	
	["cd"] = 10,
}
_M["10703"] = {
	
	["id"] = 10703,	
	["skillid"] = 107,	
	["level"] = 3,	
	["money"] = 30,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 40,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 5,	
	["morale"] = 10,	
	["cd"] = 10,
}
_M["10704"] = {
	
	["id"] = 10704,	
	["skillid"] = 107,	
	["level"] = 4,	
	["money"] = 40,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 50,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 6,	
	["morale"] = 10,	
	["cd"] = 10,
}
_M["10705"] = {
	
	["id"] = 10705,	
	["skillid"] = 107,	
	["level"] = 5,	
	["money"] = 50,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 60,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 7,	
	["morale"] = 10,	
	["cd"] = 10,
}
_M["10801"] = {
	
	["id"] = 10801,	
	["skillid"] = 108,	
	["level"] = 1,	
	["money"] = 10,	
	["hp"] = 10,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 3,	
	["morale"] = 10,	
	["cd"] = 10,
}
_M["10802"] = {
	
	["id"] = 10802,	
	["skillid"] = 108,	
	["level"] = 2,	
	["money"] = 20,	
	["hp"] = 20,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 10,	
	["cd"] = 10,
}
_M["10803"] = {
	
	["id"] = 10803,	
	["skillid"] = 108,	
	["level"] = 3,	
	["money"] = 30,	
	["hp"] = 30,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 5,	
	["morale"] = 10,	
	["cd"] = 10,
}
_M["10804"] = {
	
	["id"] = 10804,	
	["skillid"] = 108,	
	["level"] = 4,	
	["money"] = 40,	
	["hp"] = 40,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 6,	
	["morale"] = 10,	
	["cd"] = 10,
}
_M["10805"] = {
	
	["id"] = 10805,	
	["skillid"] = 108,	
	["level"] = 5,	
	["money"] = 50,	
	["hp"] = 50,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 7,	
	["morale"] = 10,	
	["cd"] = 10,
}
_M["10901"] = {
	
	["id"] = 10901,	
	["skillid"] = 109,	
	["level"] = 1,	
	["money"] = 10,	
	["hp"] = 50,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 10,	
	["attack_speed"] = 5,	
	["time_duration"] = 3,	
	["morale"] = 10,	
	["cd"] = 10,
}
_M["10902"] = {
	
	["id"] = 10902,	
	["skillid"] = 109,	
	["level"] = 2,	
	["money"] = 20,	
	["hp"] = 60,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 20,	
	["attack_speed"] = 10,	
	["time_duration"] = 4,	
	["morale"] = 10,	
	["cd"] = 10,
}
_M["10903"] = {
	
	["id"] = 10903,	
	["skillid"] = 109,	
	["level"] = 3,	
	["money"] = 30,	
	["hp"] = 70,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 30,	
	["attack_speed"] = 15,	
	["time_duration"] = 5,	
	["morale"] = 10,	
	["cd"] = 10,
}
_M["10904"] = {
	
	["id"] = 10904,	
	["skillid"] = 109,	
	["level"] = 4,	
	["money"] = 40,	
	["hp"] = 80,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 40,	
	["attack_speed"] = 20,	
	["time_duration"] = 6,	
	["morale"] = 10,	
	["cd"] = 10,
}
_M["10905"] = {
	
	["id"] = 10905,	
	["skillid"] = 109,	
	["level"] = 5,	
	["money"] = 50,	
	["hp"] = 90,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 50,	
	["attack_speed"] = 25,	
	["time_duration"] = 7,	
	["morale"] = 10,	
	["cd"] = 10,
}
_M["11001"] = {
	
	["id"] = 11001,	
	["skillid"] = 110,	
	["level"] = 1,	
	["money"] = 10,	
	["hp"] = 0,	
	["attack"] = 10,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 3,	
	["morale"] = 10,	
	["cd"] = 10,
}
_M["11002"] = {
	
	["id"] = 11002,	
	["skillid"] = 110,	
	["level"] = 2,	
	["money"] = 20,	
	["hp"] = 0,	
	["attack"] = 20,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 10,	
	["cd"] = 10,
}
_M["11003"] = {
	
	["id"] = 11003,	
	["skillid"] = 110,	
	["level"] = 3,	
	["money"] = 30,	
	["hp"] = 0,	
	["attack"] = 30,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 5,	
	["morale"] = 10,	
	["cd"] = 10,
}
_M["11004"] = {
	
	["id"] = 11004,	
	["skillid"] = 110,	
	["level"] = 4,	
	["money"] = 40,	
	["hp"] = 0,	
	["attack"] = 40,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 6,	
	["morale"] = 10,	
	["cd"] = 10,
}
_M["11005"] = {
	
	["id"] = 11005,	
	["skillid"] = 110,	
	["level"] = 5,	
	["money"] = 50,	
	["hp"] = 0,	
	["attack"] = 50,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 7,	
	["morale"] = 10,	
	["cd"] = 10,
}
_M["12101"] = {
	
	["id"] = 12101,	
	["skillid"] = 121,	
	["level"] = 1,	
	["money"] = 10,	
	["hp"] = 1783,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 5,	
	["morale"] = 510,	
	["cd"] = 10,
}
_M["12102"] = {
	
	["id"] = 12102,	
	["skillid"] = 121,	
	["level"] = 2,	
	["money"] = 20,	
	["hp"] = 2080,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 5,	
	["morale"] = 510,	
	["cd"] = 10,
}
_M["12103"] = {
	
	["id"] = 12103,	
	["skillid"] = 121,	
	["level"] = 3,	
	["money"] = 30,	
	["hp"] = 2378,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 5,	
	["morale"] = 510,	
	["cd"] = 10,
}
_M["12104"] = {
	
	["id"] = 12104,	
	["skillid"] = 121,	
	["level"] = 4,	
	["money"] = 40,	
	["hp"] = 2675,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 5,	
	["morale"] = 510,	
	["cd"] = 10,
}
_M["12105"] = {
	
	["id"] = 12105,	
	["skillid"] = 121,	
	["level"] = 5,	
	["money"] = 50,	
	["hp"] = 2972,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 5,	
	["morale"] = 510,	
	["cd"] = 10,
}
_M["12201"] = {
	
	["id"] = 12201,	
	["skillid"] = 122,	
	["level"] = 1,	
	["money"] = 10,	
	["hp"] = 595,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 5,	
	["morale"] = 510,	
	["cd"] = 10,
}
_M["12202"] = {
	
	["id"] = 12202,	
	["skillid"] = 122,	
	["level"] = 2,	
	["money"] = 20,	
	["hp"] = 694,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 5,	
	["morale"] = 510,	
	["cd"] = 10,
}
_M["12203"] = {
	
	["id"] = 12203,	
	["skillid"] = 122,	
	["level"] = 3,	
	["money"] = 30,	
	["hp"] = 793,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 5,	
	["morale"] = 510,	
	["cd"] = 10,
}
_M["12204"] = {
	
	["id"] = 12204,	
	["skillid"] = 122,	
	["level"] = 4,	
	["money"] = 40,	
	["hp"] = 892,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 5,	
	["morale"] = 510,	
	["cd"] = 10,
}
_M["12205"] = {
	
	["id"] = 12205,	
	["skillid"] = 122,	
	["level"] = 5,	
	["money"] = 50,	
	["hp"] = 991,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 5,	
	["morale"] = 510,	
	["cd"] = 10,
}
_M["12301"] = {
	
	["id"] = 12301,	
	["skillid"] = 123,	
	["level"] = 1,	
	["money"] = 10,	
	["hp"] = 0,	
	["attack"] = 332,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 390,	
	["cd"] = 8,
}
_M["12302"] = {
	
	["id"] = 12302,	
	["skillid"] = 123,	
	["level"] = 2,	
	["money"] = 20,	
	["hp"] = 0,	
	["attack"] = 388,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 390,	
	["cd"] = 8,
}
_M["12303"] = {
	
	["id"] = 12303,	
	["skillid"] = 123,	
	["level"] = 3,	
	["money"] = 30,	
	["hp"] = 0,	
	["attack"] = 443,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 390,	
	["cd"] = 8,
}
_M["12304"] = {
	
	["id"] = 12304,	
	["skillid"] = 123,	
	["level"] = 4,	
	["money"] = 40,	
	["hp"] = 0,	
	["attack"] = 499,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 390,	
	["cd"] = 8,
}
_M["12305"] = {
	
	["id"] = 12305,	
	["skillid"] = 123,	
	["level"] = 5,	
	["money"] = 50,	
	["hp"] = 0,	
	["attack"] = 554,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 390,	
	["cd"] = 8,
}
_M["12401"] = {
	
	["id"] = 12401,	
	["skillid"] = 124,	
	["level"] = 1,	
	["money"] = 10,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 332,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 390,	
	["cd"] = 8,
}
_M["12402"] = {
	
	["id"] = 12402,	
	["skillid"] = 124,	
	["level"] = 2,	
	["money"] = 20,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 388,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 390,	
	["cd"] = 8,
}
_M["12403"] = {
	
	["id"] = 12403,	
	["skillid"] = 124,	
	["level"] = 3,	
	["money"] = 30,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 443,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 390,	
	["cd"] = 8,
}
_M["12404"] = {
	
	["id"] = 12404,	
	["skillid"] = 124,	
	["level"] = 4,	
	["money"] = 40,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 499,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 390,	
	["cd"] = 8,
}
_M["12405"] = {
	
	["id"] = 12405,	
	["skillid"] = 124,	
	["level"] = 5,	
	["money"] = 50,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 554,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 390,	
	["cd"] = 8,
}
_M["12501"] = {
	
	["id"] = 12501,	
	["skillid"] = 125,	
	["level"] = 1,	
	["money"] = 10,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 101,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 390,	
	["cd"] = 8,
}
_M["12502"] = {
	
	["id"] = 12502,	
	["skillid"] = 125,	
	["level"] = 2,	
	["money"] = 20,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 118,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 390,	
	["cd"] = 8,
}
_M["12503"] = {
	
	["id"] = 12503,	
	["skillid"] = 125,	
	["level"] = 3,	
	["money"] = 30,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 135,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 390,	
	["cd"] = 8,
}
_M["12504"] = {
	
	["id"] = 12504,	
	["skillid"] = 125,	
	["level"] = 4,	
	["money"] = 40,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 152,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 390,	
	["cd"] = 8,
}
_M["12505"] = {
	
	["id"] = 12505,	
	["skillid"] = 125,	
	["level"] = 5,	
	["money"] = 50,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 169,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 390,	
	["cd"] = 8,
}
_M["12601"] = {
	
	["id"] = 12601,	
	["skillid"] = 126,	
	["level"] = 1,	
	["money"] = 10,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 46,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 390,	
	["cd"] = 8,
}
_M["12602"] = {
	
	["id"] = 12602,	
	["skillid"] = 126,	
	["level"] = 2,	
	["money"] = 20,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 54,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 390,	
	["cd"] = 8,
}
_M["12603"] = {
	
	["id"] = 12603,	
	["skillid"] = 126,	
	["level"] = 3,	
	["money"] = 30,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 62,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 390,	
	["cd"] = 8,
}
_M["12604"] = {
	
	["id"] = 12604,	
	["skillid"] = 126,	
	["level"] = 4,	
	["money"] = 40,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 69,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 390,	
	["cd"] = 8,
}
_M["12605"] = {
	
	["id"] = 12605,	
	["skillid"] = 126,	
	["level"] = 5,	
	["money"] = 50,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 77,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 390,	
	["cd"] = 8,
}
_M["12701"] = {
	
	["id"] = 12701,	
	["skillid"] = 127,	
	["level"] = 1,	
	["money"] = 10,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 2,	
	["time_duration"] = 3,	
	["morale"] = 300,	
	["cd"] = 6,
}
_M["12702"] = {
	
	["id"] = 12702,	
	["skillid"] = 127,	
	["level"] = 2,	
	["money"] = 20,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 2,	
	["time_duration"] = 3,	
	["morale"] = 300,	
	["cd"] = 6,
}
_M["12703"] = {
	
	["id"] = 12703,	
	["skillid"] = 127,	
	["level"] = 3,	
	["money"] = 30,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 2,	
	["time_duration"] = 3,	
	["morale"] = 300,	
	["cd"] = 6,
}
_M["12704"] = {
	
	["id"] = 12704,	
	["skillid"] = 127,	
	["level"] = 4,	
	["money"] = 40,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 3,	
	["time_duration"] = 3,	
	["morale"] = 300,	
	["cd"] = 6,
}
_M["12705"] = {
	
	["id"] = 12705,	
	["skillid"] = 127,	
	["level"] = 5,	
	["money"] = 50,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 3,	
	["time_duration"] = 3,	
	["morale"] = 300,	
	["cd"] = 6,
}
_M["12801"] = {
	
	["id"] = 12801,	
	["skillid"] = 128,	
	["level"] = 1,	
	["money"] = 10,	
	["hp"] = 0,	
	["attack"] = 332,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 390,	
	["cd"] = 8,
}
_M["12802"] = {
	
	["id"] = 12802,	
	["skillid"] = 128,	
	["level"] = 2,	
	["money"] = 20,	
	["hp"] = 0,	
	["attack"] = 388,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 390,	
	["cd"] = 8,
}
_M["12803"] = {
	
	["id"] = 12803,	
	["skillid"] = 128,	
	["level"] = 3,	
	["money"] = 30,	
	["hp"] = 0,	
	["attack"] = 443,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 390,	
	["cd"] = 8,
}
_M["12804"] = {
	
	["id"] = 12804,	
	["skillid"] = 128,	
	["level"] = 4,	
	["money"] = 40,	
	["hp"] = 0,	
	["attack"] = 499,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 390,	
	["cd"] = 8,
}
_M["12805"] = {
	
	["id"] = 12805,	
	["skillid"] = 128,	
	["level"] = 5,	
	["money"] = 50,	
	["hp"] = 0,	
	["attack"] = 554,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 390,	
	["cd"] = 8,
}
_M["12901"] = {
	
	["id"] = 12901,	
	["skillid"] = 129,	
	["level"] = 1,	
	["money"] = 10,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 332,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 390,	
	["cd"] = 8,
}
_M["12902"] = {
	
	["id"] = 12902,	
	["skillid"] = 129,	
	["level"] = 2,	
	["money"] = 20,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 388,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 390,	
	["cd"] = 8,
}
_M["12903"] = {
	
	["id"] = 12903,	
	["skillid"] = 129,	
	["level"] = 3,	
	["money"] = 30,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 443,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 390,	
	["cd"] = 8,
}
_M["12904"] = {
	
	["id"] = 12904,	
	["skillid"] = 129,	
	["level"] = 4,	
	["money"] = 40,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 499,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 390,	
	["cd"] = 8,
}
_M["12905"] = {
	
	["id"] = 12905,	
	["skillid"] = 129,	
	["level"] = 5,	
	["money"] = 50,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 554,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 390,	
	["cd"] = 8,
}
_M["13001"] = {
	
	["id"] = 13001,	
	["skillid"] = 130,	
	["level"] = 1,	
	["money"] = 10,	
	["hp"] = 0,	
	["attack"] = 443,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 3,	
	["morale"] = 300,	
	["cd"] = 6,
}
_M["13002"] = {
	
	["id"] = 13002,	
	["skillid"] = 130,	
	["level"] = 2,	
	["money"] = 20,	
	["hp"] = 0,	
	["attack"] = 517,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 3,	
	["morale"] = 300,	
	["cd"] = 6,
}
_M["13003"] = {
	
	["id"] = 13003,	
	["skillid"] = 130,	
	["level"] = 3,	
	["money"] = 30,	
	["hp"] = 0,	
	["attack"] = 590,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 3,	
	["morale"] = 300,	
	["cd"] = 6,
}
_M["13004"] = {
	
	["id"] = 13004,	
	["skillid"] = 130,	
	["level"] = 4,	
	["money"] = 40,	
	["hp"] = 0,	
	["attack"] = 664,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 3,	
	["morale"] = 300,	
	["cd"] = 6,
}
_M["13005"] = {
	
	["id"] = 13005,	
	["skillid"] = 130,	
	["level"] = 5,	
	["money"] = 50,	
	["hp"] = 0,	
	["attack"] = 738,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 3,	
	["morale"] = 300,	
	["cd"] = 6,
}
_M["13101"] = {
	
	["id"] = 13101,	
	["skillid"] = 131,	
	["level"] = 1,	
	["money"] = 10,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 101,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 390,	
	["cd"] = 8,
}
_M["13102"] = {
	
	["id"] = 13102,	
	["skillid"] = 131,	
	["level"] = 2,	
	["money"] = 20,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 118,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 390,	
	["cd"] = 8,
}
_M["13103"] = {
	
	["id"] = 13103,	
	["skillid"] = 131,	
	["level"] = 3,	
	["money"] = 30,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 135,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 390,	
	["cd"] = 8,
}
_M["13104"] = {
	
	["id"] = 13104,	
	["skillid"] = 131,	
	["level"] = 4,	
	["money"] = 40,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 152,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 390,	
	["cd"] = 8,
}
_M["13105"] = {
	
	["id"] = 13105,	
	["skillid"] = 131,	
	["level"] = 5,	
	["money"] = 50,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 169,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 390,	
	["cd"] = 8,
}
_M["13201"] = {
	
	["id"] = 13201,	
	["skillid"] = 132,	
	["level"] = 1,	
	["money"] = 10,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 46,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 390,	
	["cd"] = 8,
}
_M["13202"] = {
	
	["id"] = 13202,	
	["skillid"] = 132,	
	["level"] = 2,	
	["money"] = 20,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 54,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 390,	
	["cd"] = 8,
}
_M["13203"] = {
	
	["id"] = 13203,	
	["skillid"] = 132,	
	["level"] = 3,	
	["money"] = 30,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 62,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 390,	
	["cd"] = 8,
}
_M["13204"] = {
	
	["id"] = 13204,	
	["skillid"] = 132,	
	["level"] = 4,	
	["money"] = 40,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 69,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 390,	
	["cd"] = 8,
}
_M["13205"] = {
	
	["id"] = 13205,	
	["skillid"] = 132,	
	["level"] = 5,	
	["money"] = 50,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 77,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 390,	
	["cd"] = 8,
}
_M["13301"] = {
	
	["id"] = 13301,	
	["skillid"] = 133,	
	["level"] = 1,	
	["money"] = 10,	
	["hp"] = 0,	
	["attack"] = 332,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 5,	
	["morale"] = 450,	
	["cd"] = 9,
}
_M["13302"] = {
	
	["id"] = 13302,	
	["skillid"] = 133,	
	["level"] = 2,	
	["money"] = 20,	
	["hp"] = 0,	
	["attack"] = 388,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 5,	
	["morale"] = 450,	
	["cd"] = 9,
}
_M["13303"] = {
	
	["id"] = 13303,	
	["skillid"] = 133,	
	["level"] = 3,	
	["money"] = 30,	
	["hp"] = 0,	
	["attack"] = 443,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 5,	
	["morale"] = 450,	
	["cd"] = 9,
}
_M["13304"] = {
	
	["id"] = 13304,	
	["skillid"] = 133,	
	["level"] = 4,	
	["money"] = 40,	
	["hp"] = 0,	
	["attack"] = 499,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 5,	
	["morale"] = 450,	
	["cd"] = 9,
}
_M["13305"] = {
	
	["id"] = 13305,	
	["skillid"] = 133,	
	["level"] = 5,	
	["money"] = 50,	
	["hp"] = 0,	
	["attack"] = 554,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 5,	
	["morale"] = 450,	
	["cd"] = 9,
}
_M["13401"] = {
	
	["id"] = 13401,	
	["skillid"] = 134,	
	["level"] = 1,	
	["money"] = 10,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 332,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 5,	
	["morale"] = 450,	
	["cd"] = 9,
}
_M["13402"] = {
	
	["id"] = 13402,	
	["skillid"] = 134,	
	["level"] = 2,	
	["money"] = 20,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 388,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 5,	
	["morale"] = 450,	
	["cd"] = 9,
}
_M["13403"] = {
	
	["id"] = 13403,	
	["skillid"] = 134,	
	["level"] = 3,	
	["money"] = 30,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 443,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 5,	
	["morale"] = 450,	
	["cd"] = 9,
}
_M["13404"] = {
	
	["id"] = 13404,	
	["skillid"] = 134,	
	["level"] = 4,	
	["money"] = 40,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 499,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 5,	
	["morale"] = 450,	
	["cd"] = 9,
}
_M["13405"] = {
	
	["id"] = 13405,	
	["skillid"] = 134,	
	["level"] = 5,	
	["money"] = 50,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 554,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 5,	
	["morale"] = 450,	
	["cd"] = 9,
}
_M["13501"] = {
	
	["id"] = 13501,	
	["skillid"] = 135,	
	["level"] = 1,	
	["money"] = 10,	
	["hp"] = 0,	
	["attack"] = 443,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 3,	
	["morale"] = 300,	
	["cd"] = 6,
}
_M["13502"] = {
	
	["id"] = 13502,	
	["skillid"] = 135,	
	["level"] = 2,	
	["money"] = 20,	
	["hp"] = 0,	
	["attack"] = 517,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 3,	
	["morale"] = 300,	
	["cd"] = 6,
}
_M["13503"] = {
	
	["id"] = 13503,	
	["skillid"] = 135,	
	["level"] = 3,	
	["money"] = 30,	
	["hp"] = 0,	
	["attack"] = 590,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 3,	
	["morale"] = 300,	
	["cd"] = 6,
}
_M["13504"] = {
	
	["id"] = 13504,	
	["skillid"] = 135,	
	["level"] = 4,	
	["money"] = 40,	
	["hp"] = 0,	
	["attack"] = 664,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 3,	
	["morale"] = 300,	
	["cd"] = 6,
}
_M["13505"] = {
	
	["id"] = 13505,	
	["skillid"] = 135,	
	["level"] = 5,	
	["money"] = 50,	
	["hp"] = 0,	
	["attack"] = 738,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 3,	
	["morale"] = 300,	
	["cd"] = 6,
}
_M["13601"] = {
	
	["id"] = 13601,	
	["skillid"] = 136,	
	["level"] = 1,	
	["money"] = 10,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 101,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 350,	
	["cd"] = 7,
}
_M["13602"] = {
	
	["id"] = 13602,	
	["skillid"] = 136,	
	["level"] = 2,	
	["money"] = 20,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 118,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 350,	
	["cd"] = 7,
}
_M["13603"] = {
	
	["id"] = 13603,	
	["skillid"] = 136,	
	["level"] = 3,	
	["money"] = 30,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 135,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 350,	
	["cd"] = 7,
}
_M["13604"] = {
	
	["id"] = 13604,	
	["skillid"] = 136,	
	["level"] = 4,	
	["money"] = 40,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 152,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 350,	
	["cd"] = 7,
}
_M["13605"] = {
	
	["id"] = 13605,	
	["skillid"] = 136,	
	["level"] = 5,	
	["money"] = 50,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 169,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 350,	
	["cd"] = 7,
}
_M["13701"] = {
	
	["id"] = 13701,	
	["skillid"] = 137,	
	["level"] = 1,	
	["money"] = 10,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 46,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 350,	
	["cd"] = 7,
}
_M["13702"] = {
	
	["id"] = 13702,	
	["skillid"] = 137,	
	["level"] = 2,	
	["money"] = 20,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 54,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 350,	
	["cd"] = 7,
}
_M["13703"] = {
	
	["id"] = 13703,	
	["skillid"] = 137,	
	["level"] = 3,	
	["money"] = 30,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 62,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 350,	
	["cd"] = 7,
}
_M["13704"] = {
	
	["id"] = 13704,	
	["skillid"] = 137,	
	["level"] = 4,	
	["money"] = 40,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 69,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 350,	
	["cd"] = 7,
}
_M["13705"] = {
	
	["id"] = 13705,	
	["skillid"] = 137,	
	["level"] = 5,	
	["money"] = 50,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 77,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 350,	
	["cd"] = 7,
}
_M["13801"] = {
	
	["id"] = 13801,	
	["skillid"] = 138,	
	["level"] = 1,	
	["money"] = 10,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 332,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 5,	
	["morale"] = 450,	
	["cd"] = 9,
}
_M["13802"] = {
	
	["id"] = 13802,	
	["skillid"] = 138,	
	["level"] = 2,	
	["money"] = 20,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 388,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 5,	
	["morale"] = 450,	
	["cd"] = 9,
}
_M["13803"] = {
	
	["id"] = 13803,	
	["skillid"] = 138,	
	["level"] = 3,	
	["money"] = 30,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 443,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 5,	
	["morale"] = 450,	
	["cd"] = 9,
}
_M["13804"] = {
	
	["id"] = 13804,	
	["skillid"] = 138,	
	["level"] = 4,	
	["money"] = 40,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 499,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 5,	
	["morale"] = 450,	
	["cd"] = 9,
}
_M["13805"] = {
	
	["id"] = 13805,	
	["skillid"] = 138,	
	["level"] = 5,	
	["money"] = 50,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 554,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 5,	
	["morale"] = 450,	
	["cd"] = 9,
}
_M["13901"] = {
	
	["id"] = 13901,	
	["skillid"] = 139,	
	["level"] = 1,	
	["money"] = 10,	
	["hp"] = 0,	
	["attack"] = 443,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 350,	
	["cd"] = 7,
}
_M["13902"] = {
	
	["id"] = 13902,	
	["skillid"] = 139,	
	["level"] = 2,	
	["money"] = 20,	
	["hp"] = 0,	
	["attack"] = 517,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 350,	
	["cd"] = 7,
}
_M["13903"] = {
	
	["id"] = 13903,	
	["skillid"] = 139,	
	["level"] = 3,	
	["money"] = 30,	
	["hp"] = 0,	
	["attack"] = 590,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 350,	
	["cd"] = 7,
}
_M["13904"] = {
	
	["id"] = 13904,	
	["skillid"] = 139,	
	["level"] = 4,	
	["money"] = 40,	
	["hp"] = 0,	
	["attack"] = 664,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 350,	
	["cd"] = 7,
}
_M["13905"] = {
	
	["id"] = 13905,	
	["skillid"] = 139,	
	["level"] = 5,	
	["money"] = 50,	
	["hp"] = 0,	
	["attack"] = 738,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 350,	
	["cd"] = 7,
}
_M["14001"] = {
	
	["id"] = 14001,	
	["skillid"] = 140,	
	["level"] = 1,	
	["money"] = 10,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 101,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 350,	
	["cd"] = 7,
}
_M["14002"] = {
	
	["id"] = 14002,	
	["skillid"] = 140,	
	["level"] = 2,	
	["money"] = 20,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 118,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 350,	
	["cd"] = 7,
}
_M["14003"] = {
	
	["id"] = 14003,	
	["skillid"] = 140,	
	["level"] = 3,	
	["money"] = 30,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 135,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 350,	
	["cd"] = 7,
}
_M["14004"] = {
	
	["id"] = 14004,	
	["skillid"] = 140,	
	["level"] = 4,	
	["money"] = 40,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 152,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 350,	
	["cd"] = 7,
}
_M["14005"] = {
	
	["id"] = 14005,	
	["skillid"] = 140,	
	["level"] = 5,	
	["money"] = 50,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 169,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 350,	
	["cd"] = 7,
}
_M["14101"] = {
	
	["id"] = 14101,	
	["skillid"] = 141,	
	["level"] = 1,	
	["money"] = 10,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 46,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 350,	
	["cd"] = 7,
}
_M["14102"] = {
	
	["id"] = 14102,	
	["skillid"] = 141,	
	["level"] = 2,	
	["money"] = 20,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 54,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 350,	
	["cd"] = 7,
}
_M["14103"] = {
	
	["id"] = 14103,	
	["skillid"] = 141,	
	["level"] = 3,	
	["money"] = 30,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 62,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 350,	
	["cd"] = 7,
}
_M["14104"] = {
	
	["id"] = 14104,	
	["skillid"] = 141,	
	["level"] = 4,	
	["money"] = 40,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 69,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 350,	
	["cd"] = 7,
}
_M["14105"] = {
	
	["id"] = 14105,	
	["skillid"] = 141,	
	["level"] = 5,	
	["money"] = 50,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 0,	
	["magic_defend"] = 77,	
	["attack_speed"] = 0,	
	["time_duration"] = 4,	
	["morale"] = 350,	
	["cd"] = 7,
}
_M["14201"] = {
	
	["id"] = 14201,	
	["skillid"] = 142,	
	["level"] = 1,	
	["money"] = 10,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 101,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 5,	
	["morale"] = 450,	
	["cd"] = 9,
}
_M["14202"] = {
	
	["id"] = 14202,	
	["skillid"] = 142,	
	["level"] = 2,	
	["money"] = 20,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 118,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 5,	
	["morale"] = 450,	
	["cd"] = 9,
}
_M["14203"] = {
	
	["id"] = 14203,	
	["skillid"] = 142,	
	["level"] = 3,	
	["money"] = 30,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 135,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 5,	
	["morale"] = 450,	
	["cd"] = 9,
}
_M["14204"] = {
	
	["id"] = 14204,	
	["skillid"] = 142,	
	["level"] = 4,	
	["money"] = 40,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 152,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 5,	
	["morale"] = 450,	
	["cd"] = 9,
}
_M["14205"] = {
	
	["id"] = 14205,	
	["skillid"] = 142,	
	["level"] = 5,	
	["money"] = 50,	
	["hp"] = 0,	
	["attack"] = 0,	
	["magic_attack"] = 0,	
	["defend"] = 169,	
	["magic_defend"] = 0,	
	["attack_speed"] = 0,	
	["time_duration"] = 5,	
	["morale"] = 450,	
	["cd"] = 9,
}

return _M